/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nathChatUI.dynamicUI;

import nathChatUI.NathChatClient;

/**
 *
 * @author Lazar
 */
public class NotificationBlock extends javax.swing.JPanel {

    /**
     * Creates new form NotificationBlock
     */
    public NotificationBlock() {
     
        initComponents();
        System.out.println(descriptionLabel.getPreferredSize().height);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(219,40));

        iconLabel.setText("jLabel1");
        javax.swing.ImageIcon iconLabelIcon=new javax.swing.ImageIcon(NathChatClient.path+"\\icons\\user-icon.png");
        java.awt.Image iconLabelImage=iconLabelIcon.getImage().getScaledInstance(30,30,java.awt.Image.SCALE_SMOOTH);
        iconLabelIcon.setImage(iconLabelImage);
        iconLabel.setIcon(iconLabelIcon);

        descriptionLabel.setPreferredSize(new java.awt.Dimension(183,40));
        descriptionLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(iconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void setDescription(String s){
        
        this.descriptionLabel.setText(s);
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel iconLabel;
    // End of variables declaration//GEN-END:variables
}
