/* 
 * Copyright (C) Jonathan Lazar 2019-Present
 * All Rights Reserved 2019
 */
package nathChatUI;

import java.awt.image.BufferedImage;
import java.awt.Graphics;
import java.io.IOException;
import javax.imageio.ImageIO;
import java.io.File;

/**
 *
 * @author HP
 */
public class SplashWindow extends javax.swing.JFrame {

    /**
     * Creates new form SplashWindow
     */
    
    private BufferedImage img;
    
    public SplashWindow()throws IOException{
        
        this.img=ImageIO.read(new File(NathChatClient.path+"\\icons\\nathchat-splash-image.png"));
        this.setUndecorated(true);
        initComponents();
        this.setLocation(((int)(NathChatClient.windowSize.width/2))-((int)(this.getWidth()/2))
                        ,((int)(NathChatClient.windowSize.height/2))-((int)(this.getHeight()/2)));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splashPane = new javax.swing.JPanel(){

            @Override
            protected void paintComponent(Graphics g){

                super.paintComponent(g);
                g.drawImage(SplashWindow.this.img, 0, 0, this);

            }

        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout splashPaneLayout = new javax.swing.GroupLayout(splashPane);
        splashPane.setLayout(splashPaneLayout);
        splashPaneLayout.setHorizontalGroup(
            splashPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        splashPaneLayout.setVerticalGroup(
            splashPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splashPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splashPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel splashPane;
    // End of variables declaration//GEN-END:variables
}
