/* 
 * Copyright (C) Jonathan Lazar 2019-Present
 * All Rights Reserved 2019
 */
package nathChatUI.menuDialog;

import nathChatUI.NathChatClient;
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author Anjon Rolo Lazar
 */
public class NathChatMenuDialog extends jbl.javaDev.swingSupport.MenuDialog{

    /**
     * Creates new form NathChatMenuDialog
     */
    
    private NathChatMenuDialogController controller;
    protected ImageIcon userStatusLabelIcon,showLogLabelIcon,editProfileLabelIcon,openRFolderLabelIcon;
    protected Image userStatusLabelImage_uh,showLogLabelImage_uh,editProfileLabelImage_uh,openRFolderLabelImage_uh,
                    userStatusLabelImage_h,showLogLabelImage_h,editProfileLabelImage_h,openRFolderLabelImage_h;
    public NathChatMenuDialog() {
        initComponents();
        userStatusLabelIcon=new javax.swing.ImageIcon();
        showLogLabelIcon=new javax.swing.ImageIcon();
        editProfileLabelIcon=new javax.swing.ImageIcon();
        openRFolderLabelIcon=new javax.swing.ImageIcon();
        controller=new NathChatMenuDialogController(this);
        userStatusLabelImage_uh=controller.getResizedImageLabel(
                new javax.swing.ImageIcon(NathChatClient.path+"\\icons\\status-icon-uh.png"));
        userStatusLabelImage_h=controller.getResizedImageLabel(
                new javax.swing.ImageIcon(NathChatClient.path+"\\icons\\status-icon-h.png"));
        showLogLabelImage_uh=controller.getResizedImageLabel(
                new javax.swing.ImageIcon(NathChatClient.path+"\\icons\\show-log-icon-uh.png"));
        showLogLabelImage_h=controller.getResizedImageLabel(
                new javax.swing.ImageIcon(NathChatClient.path+"\\icons\\show-log-icon-h.png"));
        editProfileLabelImage_uh=controller.getResizedImageLabel(
                new javax.swing.ImageIcon(NathChatClient.path+"\\icons\\edit-profile-icon-uh.png"));
        editProfileLabelImage_h=controller.getResizedImageLabel(
                new javax.swing.ImageIcon(NathChatClient.path+"\\icons\\edit-profile-icon-h.png"));
        openRFolderLabelImage_uh=controller.getResizedImageLabel(
                new javax.swing.ImageIcon(NathChatClient.path+"\\icons\\resource-folder-icon-uh.png"));
        openRFolderLabelImage_h=controller.getResizedImageLabel(
                new javax.swing.ImageIcon(NathChatClient.path+"\\icons\\resource-folder-icon-h.png"));
        
        controller.setIconOnLabel(userStatusLabel,userStatusLabelIcon,userStatusLabelImage_uh);
        controller.setIconOnLabel(showLogLabel,showLogLabelIcon,showLogLabelImage_uh);
        controller.setIconOnLabel(editProfileLabel,editProfileLabelIcon,editProfileLabelImage_uh);
        controller.setIconOnLabel(openRFolderLabel,openRFolderLabelIcon,openRFolderLabelImage_uh);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nathChatMenuDialogPanel = new javax.swing.JPanel();
        profilePicLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        userStatusLabel = new javax.swing.JLabel();
        showLogLabel = new javax.swing.JLabel();
        editProfileLabel = new javax.swing.JLabel();
        openRFolderLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nathChatMenuDialogPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(56, 93, 138)));

        profilePicLabel.setText("jLabel1");
        javax.swing.ImageIcon profilePicLabelIcon=new javax.swing.ImageIcon(NathChatClient.path+"\\icons\\user-icon.png");
        java.awt.Image profilePicLabelImage=profilePicLabelIcon.getImage().getScaledInstance(55,55,java.awt.Image.SCALE_SMOOTH);
        profilePicLabelIcon.setImage(profilePicLabelImage);
        profilePicLabel.setIcon(profilePicLabelIcon);

        nameLabel.setText(NathChatClient.deviceName);

        userStatusLabel.setText("Status");
        userStatusLabel.setIconTextGap(20);
        userStatusLabel.setOpaque(true);
        userStatusLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userStatusLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userStatusLabelMouseExited(evt);
            }
        });

        showLogLabel.setText("Show Log");
        showLogLabel.setIconTextGap(20);
        showLogLabel.setOpaque(true);
        showLogLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showLogLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showLogLabelMouseExited(evt);
            }
        });

        editProfileLabel.setText("Edit Profile");
        editProfileLabel.setIconTextGap(20);
        editProfileLabel.setOpaque(true);
        editProfileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editProfileLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editProfileLabelMouseExited(evt);
            }
        });

        openRFolderLabel.setText("Open Resource Folder");
        openRFolderLabel.setIconTextGap(20);
        openRFolderLabel.setOpaque(true);
        openRFolderLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openRFolderLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                openRFolderLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                openRFolderLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout nathChatMenuDialogPanelLayout = new javax.swing.GroupLayout(nathChatMenuDialogPanel);
        nathChatMenuDialogPanel.setLayout(nathChatMenuDialogPanelLayout);
        nathChatMenuDialogPanelLayout.setHorizontalGroup(
            nathChatMenuDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nathChatMenuDialogPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(profilePicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
            .addComponent(userStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(showLogLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(editProfileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(openRFolderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        nathChatMenuDialogPanelLayout.setVerticalGroup(
            nathChatMenuDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nathChatMenuDialogPanelLayout.createSequentialGroup()
                .addGroup(nathChatMenuDialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nathChatMenuDialogPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(profilePicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nathChatMenuDialogPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(showLogLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(editProfileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(openRFolderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nathChatMenuDialogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nathChatMenuDialogPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userStatusLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userStatusLabelMouseEntered
        // TODO add your handling code here:
        
        controller.userStatusLabelMouseEntr();
        
    }//GEN-LAST:event_userStatusLabelMouseEntered

    private void userStatusLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userStatusLabelMouseExited
        // TODO add your handling code here:
        
        controller.userStatusLabelMouseExt();
        
    }//GEN-LAST:event_userStatusLabelMouseExited

    private void showLogLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showLogLabelMouseEntered
        // TODO add your handling code here:
        
        controller.showLogLabelMouseEntr();
        
    }//GEN-LAST:event_showLogLabelMouseEntered

    private void showLogLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showLogLabelMouseExited
        // TODO add your handling code here:
        
        controller.showLogLabelMouseExt();
        
    }//GEN-LAST:event_showLogLabelMouseExited

    private void editProfileLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileLabelMouseEntered
        // TODO add your handling code here:
        
        controller.editProfileLabelMouseEnt();
        
    }//GEN-LAST:event_editProfileLabelMouseEntered

    private void editProfileLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileLabelMouseExited
        // TODO add your handling code here:
        
        controller.editProfileLabelMouseExt();
        
    }//GEN-LAST:event_editProfileLabelMouseExited

    private void openRFolderLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openRFolderLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_openRFolderLabelMouseClicked

    private void openRFolderLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openRFolderLabelMouseEntered
        // TODO add your handling code here:
        
        controller.openRFolderLabelMouseEnt();
        
    }//GEN-LAST:event_openRFolderLabelMouseEntered

    private void openRFolderLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openRFolderLabelMouseExited
        // TODO add your handling code here:
        
        controller.openRFolderLabelMouseExt();
        
    }//GEN-LAST:event_openRFolderLabelMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel editProfileLabel;
    protected javax.swing.JLabel nameLabel;
    private javax.swing.JPanel nathChatMenuDialogPanel;
    protected javax.swing.JLabel openRFolderLabel;
    protected javax.swing.JLabel profilePicLabel;
    protected javax.swing.JLabel showLogLabel;
    protected javax.swing.JLabel userStatusLabel;
    // End of variables declaration//GEN-END:variables
}
