/* 
 * Copyright (C) Jonathan Lazar 2019-Present
 * All Rights Reserved 2019
 */
package nathChatUI.composedMessagePanel;

import java.awt.Dimension;
import javax.swing.text.BadLocationException;
import jbl.javaDev.swingSupport.AnimatedDiag;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import nathChatEntities.GroupLayoutManager;
import nathChatUI.NathChatClient;

/**
 *
 * @author KNSI EXT1
 */
public class ComposeMessagePanel extends javax.swing.JPanel {

    /**
     * Creates new form ComposeMessagePanel
     */
    
    private ComposeMessagePanelController controller;
    private AnimatedDiag diag;
    private String userKey;
    private GroupLayoutManager<GroupLayout.SequentialGroup,GroupLayout.ParallelGroup> groupLayoutManager;
    private JScrollPane scrollPane;
    
    public ComposeMessagePanel(AnimatedDiag diag,String userKey) {
        
        this.userKey=userKey;
        this.diag=diag;
        initComponents();

        this.boldLabel.setOpaque(true);
        this.italicLabel.setOpaque(true);
        this.composedMessageTextPane.addKeyListener(
                new java.awt.event.KeyAdapter(){
                    
                    @Override
                    public void keyTyped(java.awt.event.KeyEvent evt){
                        
                        try{
                            
                            composedMessageTextPaneKeyTyped(evt);
                            
                        }
                        catch(BadLocationException b){
                            
                            b.printStackTrace();
                            
                        }
                        
                    }
                    
                }

        );
        
        this.composedMessageTextPane.setEditable(false);
        
        GroupLayout convPanelLayout=new GroupLayout(conversationPanel);
        conversationPanel.setLayout(convPanelLayout);
        
        JPanel scrollPanePanel=new JPanel();
        
        scrollPane=new JScrollPane();
        scrollPane.setBorder(null);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setPreferredSize(new Dimension(conversationPanel.getPreferredSize().width,conversationPanel.getPreferredSize().height));
        scrollPane.setViewportView(scrollPanePanel);
        
        convPanelLayout.setHorizontalGroup(
                        
            convPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(scrollPane,20,GroupLayout.PREFERRED_SIZE,Short.MAX_VALUE)
                        
        );
        convPanelLayout.setVerticalGroup(
                        
                convPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(scrollPane,20,GroupLayout.PREFERRED_SIZE,GroupLayout.PREFERRED_SIZE)
                        
        );
        
        GroupLayout scrollPanePanelLayout=new GroupLayout(scrollPanePanel);
        scrollPanePanel.setLayout(scrollPanePanelLayout);
        
        groupLayoutManager=new GroupLayoutManager<GroupLayout.SequentialGroup,GroupLayout.ParallelGroup>
            (scrollPanePanelLayout,
             scrollPanePanelLayout.createSequentialGroup(),
             scrollPanePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)){
                     
            @Override
            public void layouting(){
                
                NathChatClient.core.convFetcher(ComposeMessagePanel.this.userKey,this);
                
            }
            
        };
  
        controller=new ComposeMessagePanelController(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boldLabel = new javax.swing.JLabel();
        italicLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        composedMessageTextPane = new javax.swing.JTextPane();
        titlePanel = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        attachFileLabel = new javax.swing.JLabel();
        addPhotoLabel = new javax.swing.JLabel();
        fontComboBox = new javax.swing.JComboBox<>();
        conversationPanel = new javax.swing.JPanel();
        sendLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        boldLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boldLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boldLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boldLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boldLabelMouseExited(evt);
            }
        });

        italicLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        italicLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                italicLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                italicLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                italicLabelMouseExited(evt);
            }
        });

        composedMessageTextPane.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                composedMessageTextPaneFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(composedMessageTextPane);

        closeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });

        userLabel.setText(this.userKey);

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(closeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        javax.swing.ImageIcon closeLabelIcon=new javax.swing.ImageIcon(NathChatClient.path+"\\icons\\close-icon-uh.png");
        java.awt.Image closeLabelImage=closeLabelIcon.getImage().getScaledInstance(20,20,java.awt.Image.SCALE_SMOOTH);
        closeLabelIcon.setImage(closeLabelImage);
        closeLabel.setIcon(closeLabelIcon);
        javax.swing.ImageIcon userIcon=new javax.swing.ImageIcon(NathChatClient.path+"\\icons\\user-icon.png");
        java.awt.Image userImage=userIcon.getImage().getScaledInstance(30,30,java.awt.Image.SCALE_SMOOTH);
        userIcon.setImage(userImage);
        userLabel.setIcon(userIcon);
        userLabel.setIconTextGap(10);

        fontComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calibri", "Times New Roman", "Sans Serif", "Monospaced", "Helvetica" }));
        fontComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 153, 255)));
        fontComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontComboBoxActionPerformed(evt);
            }
        });

        conversationPanel.setPreferredSize(new java.awt.Dimension(394, 210));

        javax.swing.GroupLayout conversationPanelLayout = new javax.swing.GroupLayout(conversationPanel);
        conversationPanel.setLayout(conversationPanelLayout);
        conversationPanelLayout.setHorizontalGroup(
            conversationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );
        conversationPanelLayout.setVerticalGroup(
            conversationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        sendLabel.setPreferredSize(new java.awt.Dimension(31, 25));
        sendLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fontComboBox, 0, 113, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boldLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(italicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(attachFileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addPhotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sendLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
            .addComponent(conversationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(conversationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boldLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(italicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attachFileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addPhotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fontComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(sendLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        javax.swing.ImageIcon boldLabelIcon=new javax.swing.ImageIcon(NathChatClient.path+"\\icons\\bold-icon.png");
        java.awt.Image boldLabelImage=boldLabelIcon.getImage().getScaledInstance(20,20,java.awt.Image.SCALE_SMOOTH);
        boldLabelIcon.setImage(boldLabelImage);
        boldLabel.setIcon(boldLabelIcon);
        javax.swing.ImageIcon italicLabelIcon=new javax.swing.ImageIcon(NathChatClient.path+"\\icons\\italic-icon.png");
        java.awt.Image italicLabelImage=italicLabelIcon.getImage().getScaledInstance(20,20,java.awt.Image.SCALE_SMOOTH);
        italicLabelIcon.setImage(italicLabelImage);
        italicLabel.setIcon(italicLabelIcon);
        javax.swing.ImageIcon attachFileLabelIcon=new javax.swing.ImageIcon(NathChatClient.path+"\\icons\\attach-file-icon.png");
        java.awt.Image attachFileLabelImage=attachFileLabelIcon.getImage().getScaledInstance(25,25,java.awt.Image.SCALE_SMOOTH);
        attachFileLabelIcon.setImage(attachFileLabelImage);
        attachFileLabel.setIcon(attachFileLabelIcon);
        javax.swing.ImageIcon addPhotoLabelIcon=new javax.swing.ImageIcon(NathChatClient.path+"\\icons\\add-photo-icon.png");
        java.awt.Image addPhotoLabelImage=addPhotoLabelIcon.getImage().getScaledInstance(30,30,java.awt.Image.SCALE_SMOOTH);
        addPhotoLabelIcon.setImage(addPhotoLabelImage);
        addPhotoLabel.setIcon(addPhotoLabelIcon);
        javax.swing.ImageIcon sendLabelIcon=new javax.swing.ImageIcon(NathChatClient.path+"\\icons\\send-icon.png");
        java.awt.Image sendLabelImage=sendLabelIcon.getImage().getScaledInstance(30,30,java.awt.Image.SCALE_SMOOTH);
        sendLabelIcon.setImage(sendLabelImage);
        sendLabel.setIcon(sendLabelIcon);
    }// </editor-fold>//GEN-END:initComponents

    private void composedMessageTextPaneKeyTyped(java.awt.event.KeyEvent evt) throws BadLocationException{                                                 
        // TODO add your handling code here:
        
        controller.composeMessageTextPaneKT(evt);

    }
    
    private void boldLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boldLabelMouseClicked
        // TODO add your handling code here:
        
        controller.boldLabelMouseClk();
        
    }//GEN-LAST:event_boldLabelMouseClicked

    private void boldLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boldLabelMouseEntered
        // TODO add your handling code here:
        
        controller.boldLabelMouseEntr();
        
    }//GEN-LAST:event_boldLabelMouseEntered

    private void boldLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boldLabelMouseExited
        // TODO add your handling code here:
        
        controller.boldLabelMouseExt();
        
    }//GEN-LAST:event_boldLabelMouseExited

    private void composedMessageTextPaneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_composedMessageTextPaneFocusGained
        // TODO add your handling code here:
        
        this.composedMessageTextPane.getCaret().setVisible(true);
        
    }//GEN-LAST:event_composedMessageTextPaneFocusGained

    private void italicLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_italicLabelMouseClicked
        // TODO add your handling code here:
        
        controller.italicLabelMouseClk();
        
    }//GEN-LAST:event_italicLabelMouseClicked

    private void italicLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_italicLabelMouseEntered
        // TODO add your handling code here:
        
        controller.italicLabelMouseEntr();
        
    }//GEN-LAST:event_italicLabelMouseEntered

    private void italicLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_italicLabelMouseExited
        // TODO add your handling code here:
        
        controller.italicLabelMouseExt();
        
    }//GEN-LAST:event_italicLabelMouseExited

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        this.diag.dispose();
        NathChatClient.composeMessageList.remove(this.userKey);
        NathChatClient.composeMessageDialogCount--;
        
    }//GEN-LAST:event_closeLabelMouseClicked

    private void fontComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontComboBoxActionPerformed
        // TODO add your handling code here:
        
        controller.fontComboBoxAP();
        
    }//GEN-LAST:event_fontComboBoxActionPerformed

    private void sendLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendLabelMouseClicked
        // TODO add your handling code here:
        controller.sendLabelMouseClk(userKey);
        
    }//GEN-LAST:event_sendLabelMouseClicked
    
    
    
    public void toggleMessagePanel(){
        this.diag.activate();
    }
    
    public GroupLayoutManager<GroupLayout.SequentialGroup,GroupLayout.ParallelGroup> getGLM(){
    
        return this.groupLayoutManager;
        
    }
    
    public void reloadScrollPane(){
        
        this.scrollPane.repaint();
        this.scrollPane.revalidate();
        
    }
    
    public AnimatedDiag getAnimatedDiag(){
        
        return this.diag;
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel addPhotoLabel;
    protected javax.swing.JLabel attachFileLabel;
    protected javax.swing.JLabel boldLabel;
    private javax.swing.JLabel closeLabel;
    protected javax.swing.JTextPane composedMessageTextPane;
    private javax.swing.JPanel conversationPanel;
    protected javax.swing.JComboBox<String> fontComboBox;
    protected javax.swing.JLabel italicLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JLabel sendLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
