/* 
 * Copyright (C) Jonathan Lazar 2019-Present
 * All Rights Reserved 2019
 */
package nathChatUI.groupListPanel;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseAdapter;
import javax.swing.Box;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import nathChatUI.NathChatClient;

/**
 *
 * @author nathan
 */
public class GroupListPanel extends javax.swing.JPanel {

    /**
     * Creates new form GroupListPanel
     */
    
    private JScrollPane groupListScrollPane;
    private JPanel downPanel;
    private JLabel createMsgLabel,addGroupLabel;
    private GroupListPanelController controller;
    public GroupListPanel() {
        initComponents();
        groupListScrollPane=new javax.swing.JScrollPane(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        groupListScrollPane.setBorder(null);
        groupListScrollPane.setPreferredSize(new java.awt.Dimension(229,480));
        groupListScrollPane.setViewportView(NathChatClient.groupListTree);
        downPanel=new JPanel();
        downPanel.setBackground(Color.decode("#1F4972"));
        downPanel.setPreferredSize(new Dimension(229,40));
        //downPanel.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLUE,1));
        downPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));
        downPanel.add(Box.createRigidArea(new Dimension(5,0)));
        this.createMsgLabel=new JLabel();
        this.createMsgLabel.setPreferredSize(new Dimension(30,30));
        ImageIcon createMsgIcon=new ImageIcon(NathChatClient.path+"\\icons\\create-msg.png");
        Image createMsgImage=createMsgIcon.getImage().getScaledInstance(30,30,Image.SCALE_SMOOTH);
        createMsgIcon.setImage(createMsgImage);
        createMsgLabel.setIcon(createMsgIcon);
        downPanel.add(createMsgLabel);
        downPanel.add(Box.createRigidArea(new Dimension(5,0)));
        this.addGroupLabel=new JLabel();
        this.addGroupLabel.setPreferredSize(new Dimension(30,30));
        ImageIcon addUserIcon=new ImageIcon(NathChatClient.path+"\\icons\\add-group-icon-uh.png");
        Image addUserImage=addUserIcon.getImage().getScaledInstance(30,30,Image.SCALE_SMOOTH);
        addUserIcon.setImage(addUserImage);
        addGroupLabel.setIcon(addUserIcon);
        this.addGroupLabel.addMouseListener(
            new MouseAdapter(){
                
                @Override
                public void mouseClicked(MouseEvent e){
                    
                    controller.addGroupMouseClk();
                    
                }
                
            }
        );
        downPanel.add(addGroupLabel);
        
        GroupLayout groupListPanelLayout=new GroupLayout(this);
        this.setLayout(groupListPanelLayout);
        groupListPanelLayout.setHorizontalGroup(
                groupListPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(groupListScrollPane,GroupLayout.DEFAULT_SIZE,GroupLayout.DEFAULT_SIZE,Short.MAX_VALUE)
                    .addComponent(downPanel,GroupLayout.DEFAULT_SIZE,GroupLayout.DEFAULT_SIZE,Short.MAX_VALUE)

        );
        groupListPanelLayout.setVerticalGroup(
                groupListPanelLayout.createSequentialGroup()
                    .addComponent(groupListScrollPane,0,GroupLayout.DEFAULT_SIZE,Short.MAX_VALUE)
                    .addComponent(downPanel,50,GroupLayout.DEFAULT_SIZE,Short.MAX_VALUE)
        );
        
        controller=new GroupListPanelController(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
