/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nathChatUI.notificationPanel;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import nathChatEntities.GroupLayoutManager;
import nathChatUI.NathChatClient;

/**
 *
 * @author Lazar
 */
public class NotificationPanel extends javax.swing.JPanel {

    /**
     * Creates new form NotificationPanel
     */
    
    private JScrollPane scrollPane;
    private JPanel scrollPaneViewport;
    private GroupLayoutManager<GroupLayout.SequentialGroup,GroupLayout.ParallelGroup> groupLayoutManager;
    
    public NotificationPanel() {
        initComponents();
        
        GroupLayout notifContainerLayout=new GroupLayout(notifContainer);
        notifContainer.setLayout(notifContainerLayout);
        
        scrollPaneViewport=new JPanel();
        
        scrollPane=new JScrollPane();
        scrollPane.setBorder(null);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setPreferredSize(new Dimension(notifContainer.getPreferredSize().width,notifContainer.getPreferredSize().height));
        scrollPane.setViewportView(scrollPaneViewport);
        
        notifContainerLayout.setHorizontalGroup(
                
                notifContainerLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane,20,GroupLayout.PREFERRED_SIZE,Short.MAX_VALUE)
                
        );
        
        notifContainerLayout.setVerticalGroup(
        
                notifContainerLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane,20,GroupLayout.PREFERRED_SIZE,GroupLayout.PREFERRED_SIZE)
                
        );
        
        GroupLayout scrollPaneViewportLayout=new GroupLayout(scrollPaneViewport);
        scrollPaneViewport.setLayout(scrollPaneViewportLayout);
        
        groupLayoutManager=new GroupLayoutManager<GroupLayout.SequentialGroup,GroupLayout.ParallelGroup>
        (scrollPaneViewportLayout,
         scrollPaneViewportLayout.createSequentialGroup(),
         scrollPaneViewportLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
        ){
            
            @Override
            public void layouting(){
                
                NathChatClient.core.notifFetcher(this);
                
            }
            
            
        };
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notifTitleLabel = new javax.swing.JLabel();
        notifContainer = new javax.swing.JPanel();

        notifTitleLabel.setText("Notifications");

        notifContainer.setPreferredSize(new java.awt.Dimension(250, 396));

        javax.swing.GroupLayout notifContainerLayout = new javax.swing.GroupLayout(notifContainer);
        notifContainer.setLayout(notifContainerLayout);
        notifContainerLayout.setHorizontalGroup(
            notifContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        notifContainerLayout.setVerticalGroup(
            notifContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(notifContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notifTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(notifTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notifContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel notifContainer;
    private javax.swing.JLabel notifTitleLabel;
    // End of variables declaration//GEN-END:variables
}
